name: carnd-term3
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - pillow
    - lxml
    - jupyter
    - scipy
    - ffmpeg
    - imageio==2.1.2
    - PyYAML
    - pandas
    - scikit-learn
    - protobuf
    - pip:
        - moviepy
        - opencv-python
        - tensorflow==1.4
        - tensorflow-tensorboard
